# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [5]:
x = np.zeros(10)
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


3. Create a vector with values ranging from 10 to 49

In [6]:
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [7]:
print(v.shape)

(39,)


5. Print the type of the previous array in question 3

In [8]:
print(v.dtype)

int32


6. Print the numpy version and the configuration


In [10]:
print(np.__version__)
print(np.show_config())

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rai-y/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/rai-y/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/rai-y/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\

7. Print the dimension of the array in question 3


In [11]:
print(v.shape)

(39,)


8. Create a boolean array with all the True values

In [12]:
np.full((1,10), True, dtype=bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

9. Create a two dimensional array




In [13]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(arr2d)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [14]:
np.random.randn(3, 3)

array([[ 1.68007876, -1.15996181, -0.71178631],
       [-1.28646226,  0.62351862,  0.11744987],
       [ 0.42139818,  1.41165348, -0.25137306]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [15]:
reversed_arr = arr2d[::-1]
print(reversed_arr)

[[4 5 6]
 [1 2 3]]


12. Create a null vector of size 10 but the fifth value which is 1 

In [6]:
x = np.zeros(10)
print(x)
x[4] = 1
print(x)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


13. Create a 3x3 identity matrix

In [7]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [9]:
arr = np.array([1, 2, 3, 4, 5])
# Actual Conversion of Array 
# Note usage of astype() function 
# np.float can be changed to represent differing types 
convertedArray = arr.astype(np.float)
print("Our final array: ", str(convertedArray)) 
print("Final type: " + str(type(convertedArray[0]))) 

Our final array:  [ 1.  2.  3.  4.  5.]
Final type: <class 'numpy.float64'>


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [11]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

arr_result = np.multiply(arr1, arr2)

print(arr_result)

[[  0.   8.   3.]
 [ 28.  10.  72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [13]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

np.array_equal(arr1, arr2)

False

17. Extract all odd numbers from arr with values(0-9)

In [14]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1]

array([1, 3, 5, 7, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [17]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[a % 2 == 1] = -1
print(a)

[-1  2 -1  4 -1  6  6 -1 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [18]:
a = np.array([1,2,3,4,5,6,6,7,7,8,9])
a[5] = 12
a[6] = 12
a[7] = 12
print(a)

[ 1  2  3  4  5 12 12 12  7  8  9]


20. Create a 2d array with 1 on the border and 0 inside

In [32]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
1 on the border and 0 inside in the array
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [36]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d==5]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [40]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
arr3d[0] = 64
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [43]:
import numpy as np
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [50]:
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [55]:
arr=np.array([[0,1,2,3,4,],[5,6,7,8,9]])
arr[:2][0]

array([0, 1, 2, 3, 4])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [56]:
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[ 0.38393359  0.58622665  0.16092384  0.63807721  0.88304907]
 [ 0.2577565   0.60947276  0.09544127  0.33760521  0.89813831]
 [ 0.51396945  0.47070328  0.43517171  0.6084503   0.19317439]
 [ 0.23475217  0.81706985  0.5705665   0.57802354  0.35680107]
 [ 0.79286697  0.86381389  0.75577875  0.82038736  0.98922891]]
Minimum and Maximum Values:
0.0954412687965 0.989228911715


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [60]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [61]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [64]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
print(names = 'Will')

TypeError: 'names' is an invalid keyword argument for this function

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [65]:
arr=np.random.randint(low=1,high=15,size=(5,3) ,dtype=int)
arr

array([[10, 14,  1],
       [ 9,  6, 11],
       [ 6,  8, 12],
       [ 8,  8,  8],
       [10,  6,  6]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [66]:
arr=np.random.randint(low=1,high=16,size=(2,2,4) ,dtype=int)
arr

array([[[ 1,  4,  5, 10],
        [ 7,  9, 13, 10]],

       [[15, 13,  6, 15],
        [13,  9, 12,  6]]])

33. Swap axes of the array you created in Question 32

In [67]:
arr.swapaxes(1,2)

array([[[ 1,  7],
        [ 4,  9],
        [ 5, 13],
        [10, 10]],

       [[15, 13],
        [13,  9],
        [ 6, 12],
        [15,  6]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [74]:
arr=np.random.random(10)
res=np.where(np.sqrt(arr)<0.5,0,arr)
print(arr,res)

[ 0.24918952  0.85265873  0.45132979  0.44378683  0.01112028  0.52754534
  0.20088291  0.73273298  0.37660608  0.53864886] [ 0.          0.85265873  0.45132979  0.44378683  0.          0.52754534
  0.          0.73273298  0.37660608  0.53864886]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [73]:
a=np.random.random(12)
b=np.random.random(12)
np.maximum(a,b)

array([ 0.65283212,  0.80344042,  0.59336975,  0.65017101,  0.58724441,
        0.89925186,  0.66841074,  0.95671587,  0.25521777,  0.80361284,
        0.33440299,  0.36962386])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [72]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names=np.unique(names)
names.sort()
names

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [71]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [70]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[1]=newColumn
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [69]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [68]:
matrix=np.random.randn(5,4)
csum=matrix.cumsum()
csum

array([ 0.24157829, -0.01507613,  1.10912124,  1.59959762,  2.53000294,
        3.28813595,  4.1160363 ,  3.89114973,  5.07362959,  3.75244672,
        5.34015377,  5.94031259,  6.61457816,  5.52997252,  5.30865856,
        5.36504967,  3.58557165,  1.73555056,  0.48728598, -1.15843726])